
dataset_root: /home/liangshuqiao/hong/deepfake/rine_opt/dataset # 存储数据集的根目录
dataset_path: 
  # - Celeb-DF
  # - Celeb-DF-v2
  # - deep-fake-detection-dfd
  # - DFDC
  # - WildDeepfake
  - FF++


model_save_path: ./checkpoint
validation: True  # 是否训练后验证

